user:
  name: "{{ lookup('env', 'USER') }}"
  home: "{{ lookup('env', 'HOME') }}"
  shell: /usr/bin/zsh
  email:  knox.lively@gmail.com

hostname: animal

downloads: /tmp/downloads

base_packages:
  - git
  - rsync
  - glances
  - lsof
  - ncdu
  - tmux
  - acl
  - zsh
  - alacritty
  - jq
  - htop
  - telegram
  - vagrant
  - virtualbox


# Program vars
antigen:
  location: "{{ user.home }}/.oh-my-zsh/plugins/antigen"
  repo: "https://github.com/zsh-users/antigen.git"

ohmyzsh:
  location: "{{ user.home }}/.oh-my-zsh"
  download_url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"

tpm:
  location: "{{ user.home }}/.tmux/plugins/tpm"
  repo: "https://github.com/tmux-plugins/tpm"

vundle:
  location: "{{ user.home }}/.vim/bundle/Vundle.vim"
  repo: "https://github.com/VundleVim/Vundle.vim.git"
