# User info
user:
  name: "{{ lookup('env', 'USER') }}"
  home: "{{ lookup('env', 'HOME') }}"
  shell: /usr/bin/zsh
  email:  knox.lively@gmail.com

# Sytem info
host:
  xdg: "/run/user/1000"
  hostname: animal

downloads: /tmp/downloads

systemd:
  config_path: /lib/systemd/system
  bin_path: /usr/lib

# Repo nfo
ubuntu_keyserver_keys:
  - ACCAF35C

apt_keys:
  - https://dl.yarnpkg.com/debian/pubkey.gpg

apt_repos:
  - ppa:mmstick76/alacritty
  - ppa:wereturtle/ppa
  - ppa:atareao/telegram
  - ppa:bit-team/stable
  - ppa:stebbins/handbrake-releases

dnf_repos:
  - wereturtle/stable

# Package info
base_packages:
  - git
  - lynx
  - mutt
  - rsync
  - glances
  - lsof
  - ncdu
  - tmux
  - acl
  - zsh
  - jq
  - htop
  - net-tools
  - pwgen
  - nodejs
  - yarn
  - snapd

graphical_packages:
  - alacritty
  - vlc
  - thunderbird
  - ghostwriter
  - telegram
  - vagrant
  - virtualbox
  - hardinfo
  - backintime-qt4
  - libreoffice
  - transmission-qt

snap_packages:
  - spt

apt_packages:
  - insync
  - libasound2

aptgui_packages:
  - handbrake-gtk

# Program vars
antigen:
  location: "{{ user.home }}/.oh-my-zsh/plugins/antigen"
  repo: "https://github.com/zsh-users/antigen.git"

ohmyzsh:
  location: "{{ user.home }}/.oh-my-zsh"
  download_url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"

chrome:
  deb_url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
  rpm_url: "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"

insync:
  sources_file: "{{ apt.sources_dir }}/insync.list"

spotifyd:
  username: "{{ vault_spotifyd.username }}"
  password: "{{ vault_spotifyd.password }}"
  config: "{{ user.home }}/.config/spotifyd/spotifyd.conf"

spt:
  config_dir: "{{ user.home }}/snap/spt/current/.config/spotify-tui"
  client_id: "{{ vault_spt.client_id }}"
  client_secret: "{{ vault_spt.client_secret }}"
  device_id: ""
  port: 8888

tpm:
  location: "{{ user.home }}/.tmux/plugins/tpm"
  repo: "https://github.com/tmux-plugins/tpm"

vundle:
  location: "{{ user.home }}/.vim/bundle/Vundle.vim"
  repo: "https://github.com/VundleVim/Vundle.vim.git"
