user:
    name: knox
    group: knox
    shell: /usr/bin/zsh
    email:  knox.lively@gmail.com
    log:
        dir: log
        rotate: 8

hostname: animal

downloads: /tmp/downloads

base_packages:
    - git
    - rsync
    - glances
    - lsof
    - ncdu
    - tmux
    - acl
    - zsh
    - alacritty
