---

- name: Install trizen
  shell: |
    command -v trizen || pacman -S --noconfirm trizen

- name: Install arch dependencies via trizen
  shell: |
    trizen -S --noconfirm --needed \
        etcher \
        google-chrome \
        masterpdfeditor-free \
        burpsuite \
        ttf-ms-fonts \
        radare2-git \
        noson-app \
        rambox-bin \
        spotify \
        wxhexeditor-git
  become: no
