services:
  - docker

env:
  - BUILD_CFG=arch
  - BUILD_CFG=ubuntu
  - BUILD_CFG=fedora

script:
  - |
      if [ "$BUILD_CFG" == "ubuntu" ]; then
          docker run \
              --rm \
              -v $PWD:/tmp/ansible-workstation \
              ubuntu:latest \
              bash -c "apt update && \
                       apt -y install \
                           sudo \
                           make && \
                       cd /tmp/ansible-workstation && \
                       sudo apt-get update && \
                       sudo apt-get -y install gnupg software-properties-common && \
                       sudo apt-add-repository -y ppa:ansible/ansible && \
                       sudo apt-get update && \
                       sudo apt-get install -y ansible && \
                       make test"

      elif [ "$BUILD_CFG" == "fedora" ]; then
          docker run \
              --rm \
              -v $PWD:/tmp/ansible-workstation \
              fedora:latest \
              bash -c "echo "y" | dnf upgrade && \
                       sudo dnf install -y make gnupg ansible && \
                       cd /tmp/ansible-workstation && \
                       make test"

      elif [ "$BUILD_CFG" == "arch" ]; then
          docker run \
              --rm \
              -v $PWD:/tmp/ansible-workstation \
              alekzonder/archlinux-yaourt:latest \
              bash -c "echo "y" | sudo pacman -Scc && \
                       sudo pacman-key --populate archlinux
                       sudo pacman --noconfirm -Syu which gawk python make && \
                       cd /tmp/ansible-workstation && \
                       sudo -u yaourt bash -c 'cd /tmp/ansible-workstation && \
                       sudo pacman --noconfirm -S ansible && \
                       make test'"
      fi

after_success:
  - // e.g. send notification using Telegram

after_failure:
  - // e.g. send notification using Telegram
