---
- hosts: localhost
  connection: local

  environment:
    ANSIBLE_STDOUT_CALLBACK: debug
    ANSIBLE_LOAD_CALLBACK_PLUGINS: 1

  vars:
    gui: "{{ lookup('env', 'XDG_CURRENT_DESKTOP') }}"

  vars_files:
    - ./group_vars/vault.yml
    - ./group_vars/all.yml

  roles:
    - { role: base, become: yes }
    - { role: vim }
    - { role: tmux }
    - { role: zsh }
    - { role: fonts }
    - { role: veeam, become: yes }
    - { role: ssh_keys }
#    - { role: i3wm }
    - { role: dotfiles }
    - { role: post_install }
