---
- hosts: localhost
  connection: local

  roles:
    - { role: base, become: yes }
    - { role: users, become: yes }
    - { role: vim, become: yes }
      #    - { role: zsh }
    - { role: ssh_keys }
    - { role: dotfiles }
