---
- hosts: 127.0.0.1
  connection: local

  vars_prompt:
    - name: "secrets_config"
      prompt: "Which secrets configuration to use? e.g. secrets-YOLO"
      private: no
      confirm: yes

    - name: "secrets_repo_url"
      prompt: "Which secrets repo to use? e.g. https://gogs.yolo/user/secrets-yolo.git"
      private: no

  roles:
    - { role: dotfiles }
