---
# Download and lay down

- name: Check to see if dotfiles are installed
  stat:
    path: "{{ user.home }}/.dotfiles"
  register: dotfiles

- name: Deploy dotfiles
  shell: "{{ role_path }}/files/deploy-dotfiles.sh > /tmp/deploy-dotfiles.log"
  when: dotfiles.stat.exists == False
