- name: Add VS Code Signing Key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add VS Code Apt Repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present


- name: Update repositories cache and install "code" package
  apt:
    name: code
    update_cache: yes
