---

- name: Install debian dependencies via apt-get
  package: name={{ item }} state=latest
  with_items:
    - apt-transport-https
    - chromium
    - cmake
    - cmake-data
    - gvfs-bin
    - fonts-hack-ttf
    - i3
    - libasound2-dev
    - libcairo2-dev
    - libcurl4-openssl-dev
    - bc
    - libiw-dev
    - libmpdclient-dev
    - libxcb-ewmh-dev
    - libxcb-icccm4-dev
    - libxcb-image0-dev
    - libxcb-randr0-dev
    - libxcb-util0-dev
    - libxcb-xkb-dev
    - libxcb-xrm-dev
    - libxcb1-dev
    - network-manager-gnome
    - powerline
    - python-powerline
    - python3-powerline
    - pkg-config
    - python-xcbgen
    - python-pygments
    - silversearcher-ag
    - update-notifier
    - w3m-img
    - x11-utils
    - x11-xserver-utils
    - xbacklight
    - xcb-proto
    - zsh-common

- name: Install polybar debian dependencies via apt-get
  package: name={{ item }} state=latest
  with_items:
    - libxcb-composite0-dev

- name: Install polybar
  shell: |
    if ! which polybar; then
    mkdir -p /tmp/polybar-temp && cd /tmp/polybar-temp && \
    git clone --recursive https://github.com/jaagr/polybar && \
    mkdir -p polybar/build && cd polybar/build && \
    cmake .. && make install && \
    rm -rf /tmp/polybar-temp
    fi

- name: Install termite
  shell: |
    if ! which termite; then
    mkdir -p /tmp/termite-temp && cd /tmp/termite-temp && \
    git clone --recursive https://github.com/thestinger/termite.git && \
    git clone https://github.com/thestinger/vte-ng.git && \
    sudo apt-get install -y \
    g++ \
    libgtk-3-dev \
    gtk-doc-tools \
    gnutls-bin \
    valac \
    intltool \
    libpcre2-dev \
    libglib3.0-cil-dev \
    libgnutls28-dev \
    libgirepository1.0-dev \
    libxml2-utils \
    libtool \
    gperf && \
    echo export LIBRARY_PATH="/usr/include/gtk-3.0:$LIBRARY_PATH" && \
      cd vte-ng && ./autogen.sh && make && make install && \
      cd ../termite && make && make install && \
      ldconfig && \
      mkdir -p /lib/terminfo/x && \
      ln -s /usr/local/share/terminfo/x/xterm-termite /lib/terminfo/x/xterm-termite && \
      rm -rf /tmp/termite-temp
      fi

- name: Install playerctl
  shell: |
    cd /tmp
    curl https://api.github.com/repos/acrisci/playerctl/releases/latest | \
      grep "browser_download_url" | \
      grep "amd64.deb" | \
      cut -d : -f 2,3 | \
      tr --delete \" | \
      tr --delete " " | \
      wget -O /tmp/playerctl.deb -i - && \
    dpkg -i /tmp/playerctl.deb && \
    rm /tmp/playerctl.deb