---

### Update and upgrade all package repos

# Ubuntu
- name: apt-get update
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: apt-get upgrade
  apt:
    upgrade: dist
  when: ansible_distribution == "Ubuntu"

# Fedora
- name: dnf upgrade
  dnf:
    update_cache: yes
    name: "*"
    state: latest
  when: ansible_distribution == "Fedora"

# Arch
- name: pacman -Syu
  pacman:
    update_cache: yes
    upgrade: yes
  when: ansible_distribution == "Archlinux"


- name: Install general dependencies via package manager
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - git

- name: Installing python (Ubuntu)
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python2.7
    - python-pip
    - python3
    - python3-pip
  when: ansible_distribution == "Ubuntu"

- name: Installing python (Fedora)
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python
    - python-pip
    - python-devel
    - python3
    - python3-pip
    - python3-devel
  when: ansible_distribution == "Fedora"

- name: Installing python (Arch)
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python2
    - python2-pip
    - python
    - python-pip
  when: ansible_distribution == "Archlinux"

- name: Update pip packages
  shell: |
    pip2 install -U pip && pip3 install -U pip

#- name: Install pip2 dependencies
#  shell: |
  #      pip2 install i3ipc

#- name: Install pip3 dependencies
#  shell: |
  #    pip3 install pipenv pylint


- include_tasks: arch.yml
  when: ansible_distribution == "Archlinux"

- include_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
