---

- name: Install general dependencies via package manager
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - zsh
    - git
    - unzip

- name: Installing python (Arch)
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python2
    - python2-pip
    - python
    - python-pip
  when: ansible_distribution == "Archlinux"

- name: Installing python (Ubuntu)
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python2.7
    - python-pip
    - python3
    - python3-pip
  when: ansible_distribution == "Ubuntu"

- name: Installing python (Fedora)
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python
    - python-pip
    - python-devel.x86_64
    - python3
    - python3-pip
    - python3-devel
  when: ansible_distribution == "Fedora"

- name: Update pip packages
  shell: |
    pip2 install -U pip && pip3 install -U pip

#- name: Install pip2 dependencies
#  shell: |
  #      pip2 install i3ipc

#- name: Install pip3 dependencies
#  shell: |
  #    pip3 install pipenv pylint


- include_tasks: arch.yml
  when: ansible_distribution == "Archlinux"

- include_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
