---

# Download and install Google-Chrome

- name: Download Google-Chrome
  get_url:
    url: "{{ chrome.deb_url }}"
    dest: "{{ downloads }}/{{ chrome.deb_url | basename }}"
  when: gui != ""

- name: Install Google-Chrome
  command: "dpkg -i {{ downloads }}/{{ chrome.deb_url | basename }}"
  become: yes
  # Mostly for testing purposes as there is no DE istalled
  ignore_errors: yes
  when: gui != ""

# Remove unwanted packages
- name: Remove unwanted 'default' packages
  become: yes
  ignore_errors: yes
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ apt_packages_to_remove }}"

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

# Find and set fastest mirror
- name: Find fastest mirror
  shell: apt-select

- name: Check to see if 'sources.list' was generated
  stat:
    path: "{{ lookup('env', 'PWD') }}/sources.list"
  register: sources

- name: Backup sources.list
  copy:
    src: "/etc/apt/sources.list"
    dest: "/etc/apt/sources.list.backup"
    mode: 0600
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  become: yes
  when: sources.stat.exists == True

- name: Copy new sources.list to /etc/apt
  copy:
    src: "{{ lookup('env', 'PWD') }}/sources.list"
    dest: "/etc/apt/sources.list"
    mode: 0600
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  become: yes
  when: sources.stat.exists == True
