---

# Download and install Google-Chrome

- name: Download Google-Chrome
  get_url:
    url: "{{ chrome.deb_url }}"
    dest: "{{ downloads }}/{{ chrome.deb_url | basename }}"
  when: gui != ""

- name: Install Google-Chrome
  command: "dpkg -i {{ downloads }}/{{ chrome.deb_url | basename }}"
  become: yes
  # Mostly for testing purposes as there is no DE istalled
  ignore_errors: yes
  when: gui != ""

# Remove unwanted packages
- name: Remove unwanted 'default' packages
  become: yes
  ignore_errors: yes
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ apt_packages_to_remove }}"

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes
