---

- name: Set zsh as default shell
  become: yes
  user:
    name: "{{ user.name }}"
    shell: "{{ user.shell }}"

### Oh My Zsh
- name: Check to see if 'Oh My Zsh' is installed
  command: "ls -la {{ ohmyzsh.location }}"
  register: ohmyzsh_exists
  ignore_errors: yes

- name: Download 'Oh My Zsh' install script
  get_url:
    url: "{{ ohmyzsh.download_url }}"
    dest: "{{ downloads }}/install.sh"
  when: ohmyzsh_exists.rc != 0

- name: Set install script to executable
  file: 
    dest: "{{ downloads }}/install.sh"
    mode: a+x
  when: ohmyzsh_exists.rc != 0

- name: Install 'Oh My Zsh'
  shell: "{{ downloads }}/./install.sh"
  when: ohmyzsh_exists.rc != 0

### Antigen plugin manager
- name: Check to see if Antigen is installed
  command: "ls -la {{ antigen.location }}"
  register: antigen_exists
  ignore_errors: yes

- name: Download Antigen if not already installed
  git:
    repo: "{{ antigen.repo }}"
    dest: "{{ antigen.location }}"
  when: antigen_exists.rc != 0
