---

- name: Check to see if Veeam is installed
  stat:
    path: "{{ veeam.location }}"
  register: veeam_exists

- name: Install Veeamsnap
  apt:
    deb: "{{ veeamsnap.download_url }}"
  when: ansible_distribution == "Ubuntu" and veeam_exists.stat.exists == False

- name: Install Veeam
  apt:
    deb: "{{ veeam.download_url }}"
  when: ansible_distribution == "Ubuntu" and veeam_exists.stat.exists == False

# Fedora
# Arch
