---

- name: Ensure .ssh directory exists.
  file: 
    dest: "{{ lookup('env','HOME') }}/.ssh"
    mode: 0700 
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
    state: directory
  become: yes

- name: Install ssh keys and config
  copy: 
    src: "{{ item }}" 
    dest: "{{ lookup('env','HOME') }}/.ssh/{{ item | basename }}"
    mode: 0600
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
  with_fileglob:
    - "files/*"
  become: yes
