---
nerdfonts_install_dir: '{{user.home}}/.local/share/fonts'

# defaults file for ansible-nerdfonts

nerdfonts_fonts:
#- fontname: '3270'
- fontname: 'AnonymousPro'
#- fontname: 'Arimo'
#- fontname: 'AurulentSansMono'
#- fontname: 'BitstreamVeraSansMono'
#- fontname: 'CodeNewRoman'
#- fontname: 'Cousine'
- fontname: 'DejaVuSansMono'
- fontname: 'DroidSansMono'
#- fontname: 'FantasqueSansMono'
- fontname: 'FiraCode'
- fontname: 'FiraMono'
#- fontname: 'Go-Mono'
#- fontname: 'Gohu'
#- fontname: 'Hasklig'
#- fontname: 'HeavyData'
#- fontname: 'Hermit'
#- fontname: 'Inconsolata'
#- fontname: 'InconsolataLGC'
#- fontname: 'InconsolataGo'
#- fontname: 'Iosevka'
- fontname: 'Hack'
#- fontname: 'Lekton'
#- fontname: 'LiberationMono'
#- fontname: 'Meslo'
#- fontname: 'Monofur'
#- fontname: 'Monoid'
- fontname: 'Mononoki'
#- fontname: 'MPlus'
#- fontname: 'ProggyClean'
- fontname: 'RobotoMono'
#- fontname: 'SourceCodePro'
#- fontname: 'ShareTechMono'
#- fontname: 'SpaceMono'
#- fontname: 'Terminus'
#- fontname: 'Tinos'
- fontname: 'Ubuntu'
- fontname: 'UbuntuMono'
