---

- name: Check to see if TPM is installed
  stat:
    path: "{{ tpm.location }}"
  register: t

- name: Install TPM (Tmux Plugin Manager)
  git:
    repo: "{{ tpm.repo }}"
    dest: "{{ tpm.location }}"
  when: t.stat.exists == False
