---

- name: dnf upgrade
  dnf:
    update_cache: yes
    name: "*"
    state: latest

#- name: Install fedora dependencies via dnf
#  package:
  #  name: {{ item }} 
  #  state: latest
#  with_items:
#    - 
