---

- name: dnf upgrade
  dnf:
    update_cache: yes
    name: "*"

- name: make sure dnf-plugins.core installed
  dnf:
    name: dnf-plugins-core
    state: present

- name: Install 3rd party repositories
  command: "dnf copr enable {{ item }}"
  state: latest
  with_items:
    - {{ dnf_repos }}

#- name: Install fedora dependencies via dnf
  #package:
    #name: {{ item }}
    #state: latest
    #  with_items:
    #    - hunspell-devel
