---
# Basic vim setup. Installation of vim is handled in base

- name: Check to see if Vundle is installed
  command: "ls -la {{ vundle.location }}"
  register: vundle_exists
  ignore_errors: yes

- name: Install Vundle
  git:
    repo: "{{ vundle.repo }}"
    dest: "{{ vundle.location }}"
  when: vundle_exists.rc != 0
