---
# Basic vim setup. Installation of vim is handled in base

### Oh My Zsh
- name: Check to see if Vundle is installed
  stat:
    path: "{{ vundle.location }}"
  register: v

- name: Install Vundle
  git:
    repo: "{{ vundle.repo }}"
    dest: "{{ vundle.location }}"
  when: v.stat.exists == False
