---

- name: Installing python (Debian/Ubuntu)
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python2.7
    - python-pip
    - python3
    - python3-pip
  when: ansible_distribution != "Archlinux"

- name: Install minimal packages (Ubuntu/Debian)
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-pygments
    - ranger
    - w3m
    - w3m-img
    - silversearcher-ag
    - powerline
    - python3-powerline
    - gcc
    - g++

- name: Install antibody
  shell: |
    curl -sSL \
        $(curl -sSL https://api.github.com/repos/getantibody/antibody/releases/latest | \
        grep "browser_download_url" | \
        grep "amd64.deb" | \
        cut -d ":" -f 2,3 | \
        tr --delete \" | \
        tr --delete " ") \
     -o /tmp/antibody.deb && \
     dpkg -i /tmp/antibody.deb && \
     rm /tmp/antibody.deb